// <auto-generated />
using System;
using AgenceImmo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenceImmo.DataAccess.Migrations
{
    [DbContext(typeof(AgenceImmobiliereContext))]
    partial class AgenceImmobiliereContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Adresse", b =>
                {
                    b.Property<int>("IdAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresse"));

                    b.Property<string>("CodePostal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pays")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ville")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAdresse");

                    b.ToTable("Adresse");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Appartenance", b =>
                {
                    b.Property<int>("IdAppartenance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAppartenance"));

                    b.Property<int>("IdBien")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.HasKey("IdAppartenance");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdPersonne");

                    b.ToTable("Appartenance");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Bien", b =>
                {
                    b.Property<int>("IdBien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBien"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDisponible")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAdresse")
                        .HasColumnType("int");

                    b.Property<int>("NbreChambre")
                        .HasColumnType("int");

                    b.Property<int>("NbreFacade")
                        .HasColumnType("int");

                    b.Property<string>("PEB")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StatutActuel")
                        .HasColumnType("int");

                    b.Property<decimal>("Surface")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TypeBien")
                        .HasColumnType("int");

                    b.Property<int?>("TypeContrat")
                        .HasColumnType("int");

                    b.HasKey("IdBien");

                    b.HasIndex("IdAdresse");

                    b.ToTable("Bien");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Document", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<DateOnly>("DateAjout")
                        .HasColumnType("date");

                    b.Property<int>("IdBien")
                        .HasColumnType("int");

                    b.Property<string>("NomDocument")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdBien");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Evenement", b =>
                {
                    b.Property<int>("IdEvenement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvenement"));

                    b.Property<DateOnly?>("DateEvenement")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdBien")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("TypeEvenement")
                        .HasColumnType("int");

                    b.HasKey("IdEvenement");

                    b.HasIndex("IdBien");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Evenement");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.HistoriqueStatut", b =>
                {
                    b.Property<int>("IdHistorique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorique"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<int>("IdBien")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("IdHistorique");

                    b.HasIndex("IdBien");

                    b.ToTable("HistoriqueStatut");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.ParticipationEvenement", b =>
                {
                    b.Property<int>("IdParticipation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParticipation"));

                    b.Property<int>("IdEvenement")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.Property<int>("RolePersonne")
                        .HasColumnType("int");

                    b.HasKey("IdParticipation");

                    b.HasIndex("IdEvenement");

                    b.HasIndex("IdPersonne");

                    b.ToTable("ParticipationEvenement");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Personne", b =>
                {
                    b.Property<int>("IdPersonne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonne"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdAdresse")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPersonne");

                    b.HasIndex("IdAdresse");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("HashPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdAdresse")
                        .HasColumnType("int");

                    b.Property<string>("Identifiant")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdAdresse");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Appartenance", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Bien", "Bien")
                        .WithMany("Appartenances")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgenceImmo.DataAccess.Entities.Personne", "Personne")
                        .WithMany("Appartenances")
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Bien", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Adresse", "Adresse")
                        .WithMany("Biens")
                        .HasForeignKey("IdAdresse");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Document", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Bien", "Bien")
                        .WithMany("Documents")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bien");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Evenement", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Bien", "Bien")
                        .WithMany("Evenements")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgenceImmo.DataAccess.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Evenements")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.HistoriqueStatut", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Bien", "Bien")
                        .WithMany("HistoriqueStatuts")
                        .HasForeignKey("IdBien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bien");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.ParticipationEvenement", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Evenement", "Evenement")
                        .WithMany("Participations")
                        .HasForeignKey("IdEvenement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgenceImmo.DataAccess.Entities.Personne", "Personne")
                        .WithMany("Participations")
                        .HasForeignKey("IdPersonne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evenement");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Personne", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Adresse", "Adresse")
                        .WithMany("Personnes")
                        .HasForeignKey("IdAdresse");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Utilisateur", b =>
                {
                    b.HasOne("AgenceImmo.DataAccess.Entities.Adresse", "Adresse")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdAdresse");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Adresse", b =>
                {
                    b.Navigation("Biens");

                    b.Navigation("Personnes");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Bien", b =>
                {
                    b.Navigation("Appartenances");

                    b.Navigation("Documents");

                    b.Navigation("Evenements");

                    b.Navigation("HistoriqueStatuts");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Evenement", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Personne", b =>
                {
                    b.Navigation("Appartenances");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("AgenceImmo.DataAccess.Entities.Utilisateur", b =>
                {
                    b.Navigation("Evenements");
                });
#pragma warning restore 612, 618
        }
    }
}
